aws_dbt_snowflake_project:
  outputs:
    dev:
      account: JEHJHQK-HE98659
      database: AIRBNB
      password: Sunnyrawat@123
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: ADMIN
      warehouse: COMPUTE_WH
  target: dev
